### ISSUE TITLE
Default inheritance behaviour

### ISSUE THREAD

**Issue by gecoombs** [antarctica/PolarRoute#132]
Currently when meshing a dataset we have the option to turn on parental inheritance in the config so that cells that are split further than the resolution of the dataset will inherit the values from the larger cell that contains them. If this is not turned on the default behaviour is to return NaN. This leads to strange looking gaps in one set of data if the mesh has been split on another, higher resolution, dataset. I think it would be better to use the parental inheritance by default, unless there is a good reason to use another inheritance approach.

For example, here there are bands of empty cells in the wind resistance map as I forgot to enable parental inheritance and the mesh has split beyond the ERA5 resolution around the coast of South America:
![Screenshot from 2023-02-23 16-26-19](https://user-images.githubusercontent.com/96303082/220968784-e55cef2e-afc9-4269-a1f4-7641f31daad9.png)

**Comment by SamuelHall700** [comment]
I've moved this issue into Issues & Bugs - We'll make this change after once the re-architecture (https://github.com/orgs/antarctica/projects/2?pane=issue&itemId=15344838) is merged to avoid having to make the change twice :)

**Comment by ayat-khairy** [comment]
updated the code so that parental inheritance is used by default now. This caused 2 test cases to fail in the regression_tests as the density and thickness loaders were not configured to use parent inheritance in `create_mesh.output2016_6_80.json` and `add_vehicle.output2017_6_80.json.` I have updated the config files to address that and all the tests have passed. Will create a pull request to have this updates in integration_testing branch.

**Comment by ayat-khairy** [comment]
The parent inheritance is the default now and code merged with integration_testing branch
